services:
  - type: static
    name: systems-engineer-portfolio
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
